"""Initial migration for MySQL

Revision ID: a0f85a719ba7
Revises: 
Create Date: 2025-12-02 10:56:04.519691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0f85a719ba7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dynamic_columns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('data_type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_name', sa.String(length=200), nullable=False),
    sa.Column('sign_date', sa.Date(), nullable=False),
    sa.Column('contract_number', sa.String(length=50), nullable=False),
    sa.Column('contract_progress', sa.String(length=50), nullable=True),
    sa.Column('party_a', sa.String(length=100), nullable=False),
    sa.Column('party_b', sa.String(length=100), nullable=False),
    sa.Column('party_c', sa.String(length=100), nullable=True),
    sa.Column('project_amount', sa.Float(), nullable=True),
    sa.Column('invoice_status', sa.String(length=50), nullable=True),
    sa.Column('payment_status', sa.String(length=50), nullable=True),
    sa.Column('supply_status', sa.String(length=50), nullable=True),
    sa.Column('acceptance_status', sa.String(length=50), nullable=True),
    sa.Column('maintenance_time', sa.Date(), nullable=True),
    sa.Column('business_person', sa.String(length=100), nullable=True),
    sa.Column('project_manager', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_business_person'), ['business_person'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_contract_number'), ['contract_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_projects_contract_progress'), ['contract_progress'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_project_manager'), ['project_manager'], unique=False)

    op.create_table('project_dynamic_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('column_id', sa.Integer(), nullable=False),
    sa.Column('value_string', sa.String(length=500), nullable=True),
    sa.Column('value_integer', sa.Integer(), nullable=True),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('value_boolean', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['column_id'], ['dynamic_columns.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_notes')
    op.drop_table('project_files')
    op.drop_table('project_dynamic_values')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_project_manager'))
        batch_op.drop_index(batch_op.f('ix_projects_contract_progress'))
        batch_op.drop_index(batch_op.f('ix_projects_contract_number'))
        batch_op.drop_index(batch_op.f('ix_projects_business_person'))

    op.drop_table('projects')
    op.drop_table('users')
    op.drop_table('dynamic_columns')
    # ### end Alembic commands ###
